---
title: "UGRinvestiga"
author: "JJ Merelo"
date: "21/06/2015"
output: html_document
---

#Ránking de investigadores de informática en la UGR

```{r setup, echo=FALSE}
library(XML)
library(ggplot2)
theurl <- "http://investigacion.ugr.es/ugrinvestiga/static/BuscadorRanking/*/buscar?tipo=&rama_c=&disciplina_c=TELE_D&especialidad_c=&indicador=&periodo="
tables <- readHTMLTable(theurl)
my.table <- data.frame(Rank=c(1:length(tables$`NULL`$Citas)),Citas=as.numeric(as.character(tables$`NULL`$Citas)))

```

El [ránking de investigadores](http://investigacion.ugr.es/ugrinvestiga/static/BuscadorRanking/*/buscar?tipo=&rama_c=&disciplina_c=TELE_D&especialidad_c=&indicador=&periodo=) se elabora periódicamente por parte de [UGR investiga](http://investigacion.ugr.es/ugrinvestiga/) y está dividido por disciplinas.

El próximo gráfico refleja el número de citas por investigador, ordenado de mayor a menor y con escala y logarítmica.

```{r, echo=FALSE}
ggplot(data=my.table,aes(x=Rank,y=Citas))+geom_point()+scale_y_log10()
```

